<a href="https://colab.research.google.com/github/seknewna/AzureDeployment/blob/master/Jacobi_Gauss_Seidel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Application
Ecrire un code python pour implémenter l'algorithm de Jacobi

$$A = D - L - U \implies -T = A - D = L+U$$

Ecrire la formule simplifiée de l'algorithme de Jacobi
$$X_{i}^{(k+1)} = \left(b_i-\sum_{j=1}^nt_{ij}x_j^{(k)}\right)/a_{ii}$$

In [ ]:
import numpy as np

In [ ]:
np.zeros_like([1, 1, 1], dtype = np.double)

array([0., 0., 0.])

In [ ]:
A = np.diag(np.zeros_like([1, 1, 1], dtype = np.double))

In [ ]:
np.diagonal(A)

array([0., 0., 0.])

In [ ]:
def jacobi(A, b, tolerance=1e-10, max_iterations=10000):
  x = np.zeros_like(b, dtype=np.double)
  T = A - np.diag(np.diagonal(A))
   
  for k in range(max_iterations):
    x_old  = x.copy()
    x[:] = (b - np.dot(T, x)) / np.diagonal(A)
    
    if np.linalg.norm(x - x_old, ord=2) / np.linalg.norm(x, ord=2) < tolerance:
      print("La méthode de Jacobi converge à l'itération k = " + str(k))
      break
    if k == (max_iterations + 1):
      print("La méthode de Jacobi ne converge pas")
  return x

In [ ]:
A = np.array([[4,2,1],[-1,0,1],[2,1,4]])
b = np.array([4,2,9])
jacobi(A, b)

<ipython-input-6-7ccbec014c47>:7: RuntimeWarning: divide by zero encountered in true_divide
  x[:] = (b - np.dot(T, x)) / np.diagonal(A)
<ipython-input-6-7ccbec014c47>:9: RuntimeWarning: invalid value encountered in double_scalars
  if np.linalg.norm(x - x_old, ord=2) / np.linalg.norm(x, ord=2) < tolerance:


array([nan, nan, nan])

In [ ]:
A = np.array([[10, -1, 2, 0], [-1, -11, -1, 3], [2, -1, 10, -1], [0, 3, -1, 8]])
b = np.array([6,25,-11,15])
jacobi(A, b)

La méthode de Jacobi converge à l'itération k = 21


array([ 0.67288008, -1.59357828, -1.16118953,  2.32744316])

Ecrire un code python pour implémenter l'algorithm de Gauss-Seidel

Ecrire la formule simplifiée de l'algorithme de Gauss-Seidel
$$X_{i}^{(k+1)} = \left(b - \sum_{j=1}^{i-1}a_{ij}x_{j}^{(k+1)}-\sum_{j=i+1}^{n}a_{ij}x_{j}^{(k+1)}\right)/a_{ij}$$

In [ ]:
def gauss_seidel(A, b, tolerance=1e-10, max_iterations=10000):
  x = np.zeros_like(b, dtype=np.double)
  
  # Iterate
  for k in range(max_iterations):
    x_old  = x.copy()
    # Loop over rows
    for i in range(A.shape[0]):
      x[i] = (b[i] - np.dot(A[i,:i], x[:i]) - np.dot(A[i,(i+1):], x_old[(i+1):]))/A[i ,i]
      #Stop condition 
      if np.linalg.norm(x - x_old, ord=2) / np.linalg.norm(x, ord=2) < tolerance:
        break
  
  
  if k < (max_iterations+1):
    print("La méthode de Gauss-Seidel converge à l'itération k = " + str(k))
  else:
    print("La méthode de Gauss-Seidel ne converge pas")
  return x

In [ ]:
A = np.array([[2, -1], [1,4]])
b = np.array([8, 5])
gauss_seidel(A, b)

La méthode de Gauss-Seidel converge à l'itération k = 9999


array([4.11111111, 0.22222222])